### ISSUE TITLE
PAL/NTSC AGNUS interoperability?

### ISSUE THREAD

**Issue by DoctorDan1986** [LIV2/A500-2Meg-Chip-ram#5]
Can someone confirm this for me?  I'm reading that a PAL 318069-xx AGNUS can work on an NTSC Amiga?

https://eab.abime.net/showthread.php?t=92402

I'd love to be able to upgrade my NTSC A2000 with this board.

**Comment by LIV2** [comment]
This is correct however using a PAL Agnus in an NTSC Amiga will result in the machine outputting in a PAL mode (with bad timings because the Amiga has an oscillator for NTSC Timings) 
The screen mode can be changed in workbench back to an NTSC mode but this will not have any effect for games etc.

Running in PAL mode with an NTSC Amiga may work with some monitors / scandoublers and not others but I have not tested this myself beyond running a PAL Amiga in NTSC mode with a 1084S which worked with no issues

**Comment by DoctorDan1986** [comment]
> This is correct however using a PAL Agnus in an NTSC Amiga will result in the machine outputting in a PAL mode (with bad timings because the Amiga has an oscillator for NTSC Timings) The screen mode can be changed in workbench back to an NTSC mode but this will not have any effect for games etc.
> 
> Running in PAL mode with an NTSC Amiga may work with some monitors / scandoublers and not others but I have not tested this myself beyond running a PAL Amiga in NTSC mode with a 1084S which worked with no issues

As I'm running this into a Framemeister, this shouldn't be an issue.  Thanks for the confirmation!
